### ISSUE TITLE
release/0.1.0 - Button component

### ISSUE THREAD

**Issue by BenoitSafari** [horameus/Lupokedex#2]
_EDIT: Migration React faites en Pair-prog_

# Button component
Créer un composant web **"Button"** ré-utilisable.

## Criteres d'acceptation
- [x] Le Bouton possede deux variant => Secondaire/Primaire
- [x] Le Bouton possede un etat "désactivé"
- [x] Le style présenté est intégré au composant
- [x] La palette de style est integrée et utilise des variables CSS
- [x] La font [JetBrains Mono](https://fonts.google.com/specimen/JetBrains+Mono?query=JetBrains+Mono) est installée dans le projet

## Style
_Les valeurs en PX sont a convertir en REM_
|Type|Value|
|---|---|
|min width|90px|
|min height|33px|
|padding top/bottom|6px|
|padding left/right|16px|
|border-radius|5px|
|gap|16px|

## Maquette
![image](https://github.com/user-attachments/assets/9636c7cb-8b70-4ccb-9d1b-181873fc8d11)

## Palette
|Color|Value|
|---|---|
|palette-primary | #0066C3|
|palette-background | #1C2128|
|palette-container | #22272E|
|palette-paper | #2D333B|
|palette-text | #F5F5F5|
|palette-text-caption | #778491|
|palette-disabled | #444C56|

## Notes
Utiliser fontsource pour l'installation des fonts est une option interessante: https://fontsource.org/

**Comment by horameus** [comment]
Tu veux dire quoi par 'Le style présenté est intégré au composant' ? Je suppose que tu ne veux pas d'une class css primary et secondary ?

**Comment by BenoitSafari** [comment]
> Tu veux dire quoi par 'Le style présenté est intégré au composant' ? Je suppose que tu ne veux pas d'une class css primary et secondary ?

J'entends par la que le resultat visuel doit correspondre a la maquette.

![image](https://github.com/user-attachments/assets/9592006d-6cdb-4639-bd80-d46036e4c944)


Mais pour aller plus loin dans ta question qui semble correspondre au variant, le but du jeu c'est d'avoir une _props_ `variant` qui prendrait en parametre une _string_ "primary"/"secondary". Et c'est cette _props_ qui definira le style du button.

```html
<lupo-button variant="primary">
    Coucou, click ici pour un bon plan
</lupo-button>
```

Tu peux regler la question de plusieurs façons;
- Creer une condition dans ton composant qui resoud la classe en fonction de la props. Et donc faire des classes "LupoButton--primary"/"LupoButton--secondary" ou un truc dans ce gout la
- Utiliser un selecteur css ciblant l'attribut "variant"
