### ISSUE TITLE
Créer un fichier .vscode contenant la config de L'IDE relative au projet ainsi que les recommendations de plugins

### ISSUE THREAD

**Issue by horameus** [horameus/Lupokedex#5]

**Comment by horameus** [comment]
Comprend pas cette partie, j'ai perso crée une config minimal de ESlint pour l'instant dans un fichier eslint.config.mjs : 
`
import globals from "globals";
import pluginJs from "@eslint/js";
import tseslint from "typescript-eslint";


export default [
  {files: ["**/*.{js,mjs,cjs,ts}"]},
  {languageOptions: { globals: globals.browser }},
  pluginJs.configs.recommended,
  ...tseslint.configs.recommended,
];

`

**Comment by BenoitSafari** [comment]
> Comprend pas cette partie, j'ai perso crée une config minimal de ESlint pour l'instant dans un fichier eslint.config.mjs : ` import globals from "globals"; import pluginJs from "@eslint/js"; import tseslint from "typescript-eslint";
> 
> export default [ {files: ["**/*.{js,mjs,cjs,ts}"]}, {languageOptions: { globals: globals.browser }}, pluginJs.configs.recommended, ...tseslint.configs.recommended, ];
> 
> `

Tu peux poser ta question directement dans l'issue de la tache https://github.com/horameus/Lupokedex/issues/1
